config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  #メンバートップに関するルーティング
  root "home#top"
  get "home/about" => "home#about", as: :about

  resources :members
  get "members/:id/leave" => "members#leave", as: :leave
  patch "members/:id/out" => "members#out", as: :members_out

  resources :items

  #投稿に関するルーティング
  get "members/:member_id/posts" => "posts#index", as: :posts_index
  post "members/:member_id/items/:item_id/posts" => "posts#create", as: :posts_create
  get "members/:member_id/items/:item_id/posts/new" => "posts#new", as: :posts_new
  get "members/:member_id/items/:item_id/posts/:id/edit" => "posts#edit", as: :posts_edit
  get "members/:member_id/items/:item_id/posts/:id" => "posts#show", as: :posts_show
  patch "members/:member_id/items/:item_id/posts/:id" => "posts#update", as: :posts_update
  delete "posts/:id" => "posts#destroy", as: :posts_destroy
  post "members/:member_id/items/:item_id/posts/new_confirm" => "posts#new_confirm", as: :posts_new_confirm

  #お問い合わせに関するルーティング
  get "inquiries/complete" => "inquiries#complete", as: :inquiries_complete
  resources :inquiries
  post "inquiries/confirm" => "inquiries#confirm", as: :inquiries_confirm
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :area
	belongs_to :genre
	has_many :posts, dependent: :destroy
	validates :name, presence: true

	#画像アップローダークラスとの紐づけ
	mount_uploader :item_image, ItemImageUploader

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :authenticate_member!

  def index
    return redirect_to root_path, flash: {error: "地域を選択してください！"} if params[:area_id].blank?
  	# ユーザーに選択された地域に登録されている食品一覧を出す
    @items = Item.where(area_id: params[:area_id])
  	@vegetables = @items.where(genre_id: 1)
  	@fruits = @items.where(genre_id: 2)
  	@seafoods = @items.where(genre_id: 3)
  	@meats = @items.where(genre_id: 4)
    @area = Area.find(params[:area_id])
  	@areas = Area.where(is_deleted: false)
  end

  def show
  	@item = Item.find(params[:id])
  	@posts = Post.where(item_id: params[:id]).order(updated_at: "DESC")
  	@areas = Area.where(is_deleted: false)

    #Google Cloud Natural Languageによる判定の結果、最もスコアが高かったものを抽出
    @post = Post.where(item_id: params[:id]).order(score: "DESC").first

  	#口コミから、相場価格と特売日価格の平均値をそれぞれ算出
  	@market_price_average = Post.where(price_status: 1, item_id: params[:id]).average(:price)
  	@sale_price_average = Post.where(price_status: 0, item_id: params[:id]).average(:price)

  	#口コミから、相場価格と特売日価格の最安値を出している店舗をそれぞれ算出する
  	@market_price_minimum = Post.where(price_status: 1, item_id: params[:id]).order(:price).first
  	@sale_price_minimum = Post.where(price_status: 0, item_id: params[:id]).order(:price).first
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<div class="row">
	<!-- サイドバー -->
	<div class="col-xs-3">
		<h3 class="item_index_sidebar">ほかの地域も見る！</h3>

		<ul class="list-group">
			<% @areas.each do |area| %>
				<li class="list-group-item">
					<%= link_to items_path(:area_id => area.id) do %>
						<%= area.name %>
					<% end %>
				</li>
			<% end %>
		</ul>
	</div>
	<!-- サイドバーここまで -->

	<div class="col-xs-9">
		<div>
			<h2 class="item_index_title"><%= @area.name %>の生鮮食品一覧</h2><br>
			<h3 class="item_index_genre">＜野菜＞</h3>
		</div>

		<div class="clearfix">
			<% @vegetables.each do |vegetable| %>
				<div class="col-xs-3 item_index_detail">
					<%= image_tag vegetable.item_image.url %><br>
					<%= vegetable.name %>

					<!-- 口コミから野菜の相場価格・特売日価格の平均値をそれぞれ算出 -->
					<p>
						相場価格　　
						<% if vegetable.posts.where(price_status: 1).average(:price) == nil %>
							¥ －
						<% else %>
							¥ <%= vegetable.posts.where(price_status: 1).average(:price).round %>
						<% end %>
					</p>
					<p>
						特売日価格　
						<% if vegetable.posts.where(price_status: 0).average(:price) == nil %>
							¥ －
						<% else %>
							¥ <%= vegetable.posts.where(price_status: 0).average(:price).round %>
						<% end %>
					</p>
					<!-- 平均値ここまで -->
					<div class="item_index_button">
						<%= link_to "口コミを見る", item_path(vegetable), class: "btn btn-primary" %>
					</div>
				</div>
			<% end %>
		</div>

		<div>
			<h3 class="item_index_genre">＜果物＞</h3>
		</div>

		<div class="clearfix">
			<% @fruits.each do |fruit| %>
				<div class="col-xs-3 item_index_detail">
					<%= image_tag fruit.item_image.url %>
					<%= fruit.name %>

					<!-- 口コミから果物の相場価格・特売日価格の平均値をそれぞれ算出 -->
					<p>
						相場価格　　
						<% if fruit.posts.where(price_status: 1).average(:price) == nil %>
							¥ －
						<% else %>
							¥ <%= fruit.posts.where(price_status: 1).average(:price).round %>
						<% end %>
					</p>
					<p>
						特売日価格　
						<% if fruit.posts.where(price_status: 0).average(:price) == nil %>
							¥ －
						<% else %>
							¥ <%= fruit.posts.where(price_status: 0).average(:price).round %>
						<% end %>
					</p>
					<!-- 平均値ここまで -->
					<div class="item_index_button">
						<%= link_to "　口コミを見る　", item_path(fruit), class: "btn btn-primary" %>
					</div>
				</div>
			<% end %>
		</div>

		<div>
			<h3 class="item_index_genre">＜魚介類＞</h3>
		</div>

		<div class="clearfix">
			<% @seafoods.each do |seafood| %>
				<div class="col-xs-3 item_index_detail">
					<%= image_tag seafood.item_image.url %>
					<%= seafood.name %>

					<!-- 口コミから魚介類の相場価格・特売日価格の平均値をそれぞれ算出 -->
					<p>
						相場価格　　
						<% if seafood.posts.where(price_status: 1).average(:price) == nil %>
							¥ －
						<% else %>
							¥ <%= seafood.posts.where(price_status: 1).average(:price).round %>
						<% end %>
					</p>
					<p>
						特売日価格　
						<% if seafood.posts.where(price_status: 0).average(:price) == nil %>
							¥ －
						<% else %>
							¥ <%= seafood.posts.where(price_status: 0).average(:price).round %>
						<% end %>
					</p>
					<!-- 平均値ここまで -->
					<div class="item_index_button">
						<%= link_to "　口コミを見る　", item_path(seafood), class: "btn btn-primary" %>
					</div>
				</div>
			<% end %>
		</div>

		<div>
			<h3 class="item_index_genre">＜肉類・卵＞</h3>
		</div>

		<div class="clearfix">
			<% @meats.each do |meat| %>
				<div class="col-xs-3 item_index_detail">
					<%= image_tag meat.item_image.url %>
					<%= meat.name %>

					<!-- 口コミから肉類の相場価格・特売日価格の平均値をそれぞれ算出 -->
					<p>
						相場価格　　
						<% if meat.posts.where(price_status: 1).average(:price) == nil %>
							¥ －
						<% else %>
							¥ <%= meat.posts.where(price_status: 1).average(:price).round %>
						<% end %>
					</p>
					<p>
						特売日価格　
						<% if meat.posts.where(price_status: 0).average(:price) == nil %>
							¥ －
						<% else %>
							¥ <%= meat.posts.where(price_status: 0).average(:price).round %>
						<% end %>
					</p>
					<!-- 平均値ここまで -->
					<div class="item_index_button">
						<%= link_to "　口コミを見る　", item_path(meat), class: "btn btn-primary" %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/items/show.html.erb
<%= flash[:success] %>

<div class="row">
	<!-- サイドバー -->
	<div class="col-xs-2">
		<h3 class="item_show_sidebar">ほかの地域</h3>

		<ul class="list-group">
			<% @areas.each do |area| %>
				<li class="list-group-item">
					<%= link_to items_path(:area_id => area.id) do %>
						<%= area.name %>
					<% end %>
				</li>
			<% end %>
		</ul>
	</div>
	<!-- サイドバーここまで -->

	<div class="col-xs-10">
		<div>
			<h2 class="item_show_title">商品詳細</h2>
		</div>

		<div class="item_show_image_area">
			<div class="item_show_item_image">
				<%= image_tag @item.item_image.detail.url %>
			</div>

			<div>
				<h3><%= @item.name %></h3>
			</div>
		</div>

		<div class="item_show_price">
			<h4 class="item_show_price_title">相場価格</h4>
			<% if @market_price_average == nil %>
				<h4>¥　－</h4>
			<% else %>
				<h4>¥　<%= @market_price_average.round %></h4>
			<% end %>

			<h4>
				一番相場価格がお得な店舗：
				<% if @market_price_minimum == nil %>
					ー
				<% else %>
					<%= @market_price_minimum.shop_name %>
				<% end %>
			</h4>
		</div>

		<div class="item_show_price">
			<h4 class="item_show_price_title">特売日価格</h4>
			<% if @sale_price_average == nil %>
				<h4>¥　－</h4>
			<% else %>
				<h4>¥　<%= @sale_price_average.round %></h4>
			<% end %>

			<h4>
				一番特売日価格がお得な店舗：
				<% if @sale_price_minimum == nil %>
					ー
				<% else %>
					<%= @sale_price_minimum.shop_name %>
				<% end %>
			</h4>
		</div>

		<div class="item_show_new_post_area">
			<% if @posts.blank? %>
				<h4>最初の口コミを投稿してみませんか？</h4>
			<% else %>
				<h4>あなたも口コミを投稿してみませんか？</h4>
			<% end %>

			<div>
				<%= link_to "　投稿する　", posts_new_path(:member_id => current_member.id, :item_id => @item.id), class: "btn btn-primary" %>
			</div>
		</div>

		<div>
			<% if @post.blank? %>
			<% else %>
				<h3 class="item_show_pickup_post">ピックアップ口コミ</h3>
				<table class="table table-bordered">
					<thead>
						<tr class="success">
							<th>投稿日時</th>
							<th>価格ステータス</th>
							<th>価格</th>
							<th>コメント</th>
							<th></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
							<tr>
								<td><%= @post.updated_at.to_s(:datetime_jp) %></td>
								<td><%= @post.price_status_i18n %></td>
								<td>¥　<%= @post.price %></td>
								<td>
									<%= @post.comment %><br>
									主な利用店舗：　<%= @post.shop_name %>
								</td>
								<td>
									<%= @post.member.age_i18n %>
									<%= @post.member.sex_i18n %>
								</td>
								<td><%= link_to "　詳細をみる　", posts_show_path(:member_id => current_member, :item_id => @item, :id => @post.id), class: "btn btn-primary" %></td>
							</tr>
					</tbody>
				</table>
			<% end %>
		</div>

		<div>
			<h3 class="item_show_post">みんなの口コミ</h3>
			<% if @posts.blank? %>
				<h4>口コミはまだありません。</h4>
			<% else %>
				<table class="table table-bordered">
					<thead>
						<tr class="info">
							<th>投稿日時</th>
							<th>価格ステータス</th>
							<th>価格</th>
							<th>コメント</th>
							<th></th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<% @posts.each do |post| %>
							<tr>
								<td><%= post.updated_at.to_s(:datetime_jp) %></td>
								<td><%= post.price_status_i18n %></td>
								<td>¥　<%= post.price %></td>
								<td>
									<%= post.comment %><br>
									主な利用店舗：　<%= post.shop_name %>
								</td>
								<td>
									<%= post.member.age_i18n %>
									<%= post.member.sex_i18n %>
								</td>
								<td><%= link_to "　詳細をみる　", posts_show_path(:member_id => current_member, :item_id => @item, :id => post.id), class: "btn btn-primary" %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			<% end %>
		</div>
	</div>
</div>