config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  #メンバートップに関するルーティング
  root "home#top"
  get "home/about" => "home#about", as: :about

  resources :members
  get "members/:id/leave" => "members#leave", as: :leave
  patch "members/:id/out" => "members#out", as: :members_out

  resources :items

  #投稿に関するルーティング
  get "members/:member_id/posts" => "posts#index", as: :posts_index
  post "members/:member_id/items/:item_id/posts" => "posts#create", as: :posts_create
  get "members/:member_id/items/:item_id/posts/new" => "posts#new", as: :posts_new
  get "members/:member_id/items/:item_id/posts/:id/edit" => "posts#edit", as: :posts_edit
  get "members/:member_id/items/:item_id/posts/:id" => "posts#show", as: :posts_show
  patch "members/:member_id/items/:item_id/posts/:id" => "posts#update", as: :posts_update
  delete "posts/:id" => "posts#destroy", as: :posts_destroy
  post "members/:member_id/items/:item_id/posts/new_confirm" => "posts#new_confirm", as: :posts_new_confirm

  #お問い合わせに関するルーティング
  get "inquiries/complete" => "inquiries#complete", as: :inquiries_complete
  resources :inquiries
  post "inquiries/confirm" => "inquiries#confirm", as: :inquiries_confirm
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :favorites, dependent: :destroy
	belongs_to :member
	belongs_to :item

	enum price_status: { market_price: 1, sale_price: 0 }
	validates :price_status, inclusion: { in: Post.price_statuses.keys }

	validates :price, presence: true
	validates :shop_name, presence: true

	#いいね有無判定
	def favorited_by?(member)
		favorites.where(member_id: member.id).exists?
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_member!

  def index
    @posts = Post.where(member_id: current_member.id).order(updated_at: "DESC")
    @member = Member.find(params[:member_id])

    #アクセス制限
    if current_member.id != @member.id
      redirect_to root_path
    end
  end

  def new
    @item = Item.find(params[:item_id])

    #口コミから、相場価格と特売日価格の平均値をそれぞれ算出
    @market_price_average = Post.where(price_status: 1, item_id: params[:item_id]).average(:price)
    @sale_price_average = Post.where(price_status: 0, item_id: params[:item_id]).average(:price)
  end

  def new_confirm
    @item = Item.find(params[:item_id])
    @post = Post.new
    @post.price_status = params[:price_status]
    @post.price = params[:price]
    @post.shop_name = params[:shop_name]
    @post.comment = params[:comment]
  end

  def create
    @post = Post.new(post_params)
    @post.member_id = current_member.id
    @post.item_id = params[:item_id]
    @post.score = Language.get_data(post_params[:comment])

    #render 'posts/new'用に記載
    @item = Item.find(params[:item_id])
    @market_price_average = Post.where(price_status: 1, item_id: params[:item_id]).average(:price)
    @sale_price_average = Post.where(price_status: 0, item_id: params[:item_id]).average(:price)

    if @post.save
      flash[:success] = "口コミのご協力、ありがとうございます！"
      redirect_to item_path(params[:item_id])
    else
      render 'posts/new'
    end
  end

  def edit
    @item = Item.find(params[:item_id])
    @post = Post.find(params[:id])
    @member = Member.find(params[:member_id])
    #アクセス制限
    if current_member.id != @member.id
      redirect_to root_path
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.member_id = params[:member_id]
    @post.item_id = params[:item_id]
    @post.score = Language.get_data(post_params[:comment])
    
    if @post.update(post_params)
      flash[:success] = "編集が完了しました！"
      redirect_to posts_index_path(current_member.id)
    else
      render 'posts/edit'
    end
  end

  def show
    @post = Post.find(params[:id])
    @member = Member.find(params[:member_id])
    @item = Item.find(params[:item_id])

    #アクセス制限
    if current_member.id != @member.id
      redirect_to root_path
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "口コミを削除しました。"
      redirect_to posts_index_path(current_member.id)
    else
      render 'posts/index'
    end
  end

  private
  def post_params
    params.require(:post).permit(:price_status, :price, :shop_name, :comment)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="row">
	<div class="col-xs-3"></div>
	<div class="col-xs-9">
		<div>
			<h3 class="post_edit_title">口コミ編集</h3>
		</div>

		<div class="post_edit_item_area">
			<div class="post_edit_item_image">
				<%= image_tag @item.item_image.url %>
			</div>

			<div>
				<h4><%= @item.name %></h4>
			</div>
		</div>

		<!-- 編集内容 -->
		<%= form_with(model: @post, url: posts_update_path(:member_id => current_member, :item_id => @item.id, :id => @post.id), method: :patch, local: true) do |f| %>
			<div class="form-group">
				<%= f.label :price_status, "価格ステータス" %><br>
				<%= f.collection_radio_buttons :price_status, Post.price_statuses_i18n, :first, :last %>
			</div>

			<div class="form-group">
				<%= f.label :price, "価格（半角数字で入力）" %><br>
				<%= f.text_field :price %>　円
			</div>

			<div class="form-group">
				<%= f.label :shop_name, "主な利用店舗名（例：スーパー〇〇　××店）" %><br>
				<%= f.text_field :shop_name %>
			</div>

			<div class="form-group">
				<%= f.label :comment, "コメント（例：「いつもと比べて少し高くなったかも、、、」　「●月☆日から特売日だそうです！」）" %><br>
				<%= f.text_area :comment, size: "55x5" %>
			</div>

			<div>
				<%= f.submit "　編集する　", data: { confirm: "編集してもよろしいですか？" }, class: "btn btn-primary" %>
			</div>
		<% end %>
		<!-- 編集内容ここまで -->
	</div>
</div>

app/views/posts/index.html.erb
<%= flash[:success] %>
<%= flash[:notice] %>

<div>
	<h3 class="post_index_title">口コミ投稿一覧</h3>
</div>

<div>
	<% if @posts == [] %>
		<h4>口コミはまだありません。</h4>
	<% else %>
		<table class="table table-bordered">
			<thead>
				<tr class="info">
					<th>投稿日時</th>
					<th>地域</th>
					<th>商品名</th>
					<th>価格ステータス</th>
					<th>価格</th>
					<th>コメント</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @posts.each do |post| %>
					<tr>
						<td><%= post.updated_at.to_s(:datetime_jp) %></td>
						<td><%= post.item.area.name %></td>
						<td>
							<%= image_tag post.item.item_image.confirm.url %>
							<%= post.item.name %>
						</td>
						<td><%= post.price_status_i18n %></td>
						<td>¥ <%= post.price %></td>
						<td>
							<%= post.comment %><br>
							主な利用店舗： <%= post.shop_name %>
						</td>
						<td>
							<%= link_to "　編集する　", posts_edit_path(:member_id => current_member, :item_id => post.item_id, :id => post.id), class: "btn btn-success" %>
							<%= link_to "　削除する　", posts_destroy_path(post.id), method: :delete, data: {confirm: " 本当に削除してもよろしいですか？"}, class: "btn btn-danger" %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	<% end %>
</div>

app/views/posts/new.html.erb
<div class="row">
	<div class="col-xs-3"></div>
	<div class="col-xs-9">
		<div>
			<h3 class="post_new_title">口コミ投稿</h3>
		</div>

		<div class="post_new_item_area">
			<div class="post_new_item_image">
				<%= image_tag @item.item_image.url %>
			</div>

			<div>
				<h4><%= @item.name %></h4>
				<!-- 価格の平均額表示 -->
				<h4>
					現在の相場価格　
					<% if @market_price_average == nil %>
						<span>¥　－</span>
					<% else %>
						<span>¥　<%= @market_price_average.round %></span>
					<% end %>
				</h4>
				<h4>
					現在の特売日価格　
					<% if @sale_price_average == nil %>
						<span>¥　－</span>
					<% else %>
						<span>¥　<%= @sale_price_average.round %></span>
					<% end %>
				</h4>
				<!-- 価格の平均額表示ここまで -->
			</div>
		</div>

		<!-- 新規投稿内容 -->
		<%= form_with(url: posts_new_confirm_path(:member_id => current_member, :item_id => @item.id), method: :post, local: true) do |f| %>
			<div class="form-group">
				<%= f.label :price_status, "価格ステータス" %><br>
				<%= f.collection_radio_buttons :price_status, Post.price_statuses_i18n, :first, :last, checked: "market_price" %>
			</div>

			<div class="form-group">
				<%= f.label :price, "価格（半角数字で入力）" %><br>
				<%= f.text_field :price %>　円
			</div>

			<div class="form-group">
				<%= f.label :shop_name, "主な利用店舗名（例：スーパー〇〇　××店）" %><br>
				<%= f.text_field :shop_name %>
			</div>

			<div class="form-group">
				<%= f.label :comment, "コメント（例：「ここのお店、いつも安くておすすめです！」　「●月☆日から特売日だそうです！」）" %><br>
				<%= f.text_area :comment, size: "55x5" %>
			</div>

			<div>
				<%= f.submit "　確認する　", class: "btn btn-success" %>
			</div>
		<% end %>
		<!-- 新規投稿内容ここまで -->
	</div>
</div>

app/views/posts/new_confirm.html.erb
<div class="row">
	<div class="col-xs-1"></div>
	<div class="col-xs-11">
		<div>
			<h3 class="post_confirm_title">口コミ内容確認</h3>
			<h4>以下の内容で投稿します。よろしいですか？</h4>
		</div>

		<div>
			<table class="table table-bordered">
				<thead>
					<tr class="info">
						<th>商品名</th>
						<th>価格</th>
						<th>主な利用店舗名</th>
						<th>コメント</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							<%= image_tag @item.item_image.confirm.url %>
							<%= @item.name %>
						</td>

						<td>
							<% if @post.price_status == "market_price" %>
								相場価格
							<% else %>
								特売日価格
							<% end %>
							
							¥<%= @post.price %>
						</td>

						<td>
							<%= @post.shop_name %>
						</td>

						<td>
							<%= @post.comment %>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

		<!-- 地図表示 -->
<div class="row">
	<div class="col-xs-3"></div>
	<div class="col-xs-9">
		<div>
			<h4>主な利用店舗　地図</h4>
		</div>

		<div id="map"></div>

		<style>
			#map{
				height: 350px;
				width: 600px;
			}
		</style>

		<script type="text/javascript">
			var map;
			var service;
			var infowindow;

			function initMap() {
			  var sydney = new google.maps.LatLng(-33.867, 151.195);
			  infowindow = new google.maps.InfoWindow();
			  map = new google.maps.Map(document.getElementById("map"), {
			    center: sydney,
			    zoom: 15,
			  });
			  var request = {
			    query: "<%= @post.shop_name %>",
			    fields: ["name", "geometry"],
			  };
			  service = new google.maps.places.PlacesService(map);
			  service.findPlaceFromQuery(request, (results, status) => {
			    if (status === google.maps.places.PlacesServiceStatus.OK) {
			      for (let i = 0; i < results.length; i++) {
			        createMarker(results[i]);
			      }
			      map.setCenter(results[0].geometry.location);
			    }
			  });
			}

			function createMarker(place) {
			  var marker = new google.maps.Marker({
			    map,
			    position: place.geometry.location,
			  });
			  google.maps.event.addListener(marker, "click", () => {
			    infowindow.setContent(place.name);
			    infowindow.open(map);
			  });
			}
		</script>

		<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&libraries=places&callback=initMap">
		</script>
		<!-- 地図表示ここまで -->
	</div>
</div>

<div class="row">
	<div class="col-xs-5"></div>
	<div class="col-xs-7">
		<div class="post_confirm_button">
			<!-- 新規投稿内容 -->
			<%= form_with(model: @post, url: posts_create_path(:member_id => current_member, :item_id => @item.id), method: :post, local: true) do |f| %>
				<%= f.hidden_field :price_status %>
				<%= f.hidden_field :price %>
				<%= f.hidden_field :shop_name %>
				<%= f.hidden_field :comment %>

				<%= f.submit "　投稿する　", class: "btn btn-primary" %>
				<%= link_to "　戻る　", posts_new_path(:member_id => current_member.id, :item_id => @item.id), class: "btn btn-danger" %>
			<% end %>
			<!-- 新規投稿内容ここまで -->
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="row">
	<div class="col-xs-1"></div>
	<div class="col-xs-11">
		<div>
			<h3 class="post_show_title">口コミ詳細</h3>
		</div>

		<div>
			<table class="table table-bordered">
				<thead>
					<tr class="info">
						<th>商品名</th>
						<th>投稿日時</th>
						<th>価格</th>
						<th>コメント</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
						<tr>
							<td>
								<%= image_tag @item.item_image.confirm.url %>
								<%= @item.name %>
							</td>
							<td><%= @post.updated_at.to_s(:datetime_jp) %></td>
							<td>
								<%= @post.price_status_i18n %>　
								¥ <%= @post.price %>
							</td>
							<td>
								<%= @post.comment %><br>
								主な利用店舗：　<%= @post.shop_name %>
							</td>
							<td>
								<%= @post.member.age_i18n %>
								<%= @post.member.sex_i18n %>
							</td>
						</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-3"></div>
	<div class="col-xs-9">
		<!-- 地図表示 -->
		<div>
			<h4>主な利用店舗　地図</h4>
		</div>

		<div id="map"></div>

		<style>
			#map{
				height: 350px;
				width: 600px;
			}
		</style>

		<script type="text/javascript">
			var map;
			var service;
			var infowindow;

			function initMap() {
			  var sydney = new google.maps.LatLng(-33.867, 151.195);
			  infowindow = new google.maps.InfoWindow();
			  map = new google.maps.Map(document.getElementById("map"), {
			    center: sydney,
			    zoom: 15,
			  });
			  var request = {
			    query: "<%= @post.shop_name %>",
			    fields: ["name", "geometry"],
			  };
			  service = new google.maps.places.PlacesService(map);
			  service.findPlaceFromQuery(request, (results, status) => {
			    if (status === google.maps.places.PlacesServiceStatus.OK) {
			      for (let i = 0; i < results.length; i++) {
			        createMarker(results[i]);
			      }
			      map.setCenter(results[0].geometry.location);
			    }
			  });
			}

			function createMarker(place) {
			  var marker = new google.maps.Marker({
			    map,
			    position: place.geometry.location,
			  });
			  google.maps.event.addListener(marker, "click", () => {
			    infowindow.setContent(place.name);
			    infowindow.open(map);
			  });
			}
		</script>

		<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&libraries=places&callback=initMap">
		</script>
		<!-- 地図表示ここまで -->
	</div>
</div>

<div class="post_show_button">
	<%= link_to "商品ページに戻る", item_path(@item), class: "btn btn-success" %>
</div>