config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  #メンバートップに関するルーティング
  root "home#top"
  get "home/about" => "home#about", as: :about

  resources :members
  get "members/:id/leave" => "members#leave", as: :leave
  patch "members/:id/out" => "members#out", as: :members_out

  resources :items

  #投稿に関するルーティング
  get "members/:member_id/posts" => "posts#index", as: :posts_index
  post "members/:member_id/items/:item_id/posts" => "posts#create", as: :posts_create
  get "members/:member_id/items/:item_id/posts/new" => "posts#new", as: :posts_new
  get "members/:member_id/items/:item_id/posts/:id/edit" => "posts#edit", as: :posts_edit
  get "members/:member_id/items/:item_id/posts/:id" => "posts#show", as: :posts_show
  patch "members/:member_id/items/:item_id/posts/:id" => "posts#update", as: :posts_update
  delete "posts/:id" => "posts#destroy", as: :posts_destroy
  post "members/:member_id/items/:item_id/posts/new_confirm" => "posts#new_confirm", as: :posts_new_confirm

  #お問い合わせに関するルーティング
  get "inquiries/complete" => "inquiries#complete", as: :inquiries_complete
  resources :inquiries
  post "inquiries/confirm" => "inquiries#confirm", as: :inquiries_confirm
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>新生活応援！生鮮食品相場チェッカー</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/13d4e31cf2.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="all_container">
    <!-- ヘッダー -->
    <header class="header_container">
      <div class="header_container_item">
        <a href="/" class="header_logo"><span>ヘッダーロゴリンク</span></a>
      </div>
      <div class="header_container_item">
        <% if member_signed_in? %>
          <p>ようこそ、<%= current_member.name %>さん！</p>
        <% end %>
      </div>

      <div class="header_container_item">
        <ul class="header_list">
          <% if member_signed_in? %>
            <li>
              <%= link_to root_path, class: "btn btn-default header_list_item" do %>
                <i class="fas fa-desktop"> トップ</i>
              <% end %>
            </li>
            <li>
              <%= link_to member_path(current_member), class: "btn btn-default header_list_item" do %>
                <i class="fas fa-user-circle"> マイページ</i>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_member_session_path, method: :delete, class: "btn btn-default header_list_item" do%>
                <i class="fas fa-sign-out-alt"> ログアウト</i>
              <% end %>
            </li>
            <li>
              <%= link_to new_inquiry_path, class: "btn btn-default header_list_item" do %>
                <i class="fas fa-paper-plane"> お問い合わせ</i>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to about_path, class: "btn btn-default header_list_item" do %>
                <i class="fas fa-info-circle"> このサイトについて</i>
              <% end %>
            </li>
            <li>
              <%= link_to new_member_registration_path, class: "btn btn-default header_list_item" do %>
                <i class="fas fa-user"> 新規会員登録</i>
              <% end %>
            </li>
            <li>
              <%= link_to new_member_session_path, class: "btn btn-default header_list_item" do %>
                <i class="fas fa-sign-in-alt"> ログイン</i>
              <% end %>
            </li>
            <li>
              <%= link_to new_inquiry_path, class: "btn btn-default header_list_item" do %>
                <i class="fas fa-paper-plane"> お問い合わせ</i>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </header>
    <!-- ヘッダーここまで -->

    <div class="container">
      <body>
        <%= yield %>

        <!-- ページトップに戻るボタン -->
        <span id="back">
          <a href="#">
            <%= image_tag asset_path("arrow.png") %>
          </a>
        </span>
        <!-- ページトップに戻るボタンここまで -->
      </body>
    </div>

    <!-- フッター -->
    <footer>
      <div>
        © 新生活応援！生鮮食品相場チェッカー, Inc. All Rights Reserved.　
        <%= link_to "管理者ページ", new_admin_user_session_path %>
      </div>
    </footer>
    <!-- フッターここまで -->
  </div>
</html>