config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  #メンバートップに関するルーティング
  root "home#top"
  get "home/about" => "home#about", as: :about

  resources :members
  get "members/:id/leave" => "members#leave", as: :leave
  patch "members/:id/out" => "members#out", as: :members_out

  resources :items

  #投稿に関するルーティング
  get "members/:member_id/posts" => "posts#index", as: :posts_index
  post "members/:member_id/items/:item_id/posts" => "posts#create", as: :posts_create
  get "members/:member_id/items/:item_id/posts/new" => "posts#new", as: :posts_new
  get "members/:member_id/items/:item_id/posts/:id/edit" => "posts#edit", as: :posts_edit
  get "members/:member_id/items/:item_id/posts/:id" => "posts#show", as: :posts_show
  patch "members/:member_id/items/:item_id/posts/:id" => "posts#update", as: :posts_update
  delete "posts/:id" => "posts#destroy", as: :posts_destroy
  post "members/:member_id/items/:item_id/posts/new_confirm" => "posts#new_confirm", as: :posts_new_confirm

  #お問い合わせに関するルーティング
  get "inquiries/complete" => "inquiries#complete", as: :inquiries_complete
  resources :inquiries
  post "inquiries/confirm" => "inquiries#confirm", as: :inquiries_confirm
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :area

  validates :name, presence: true

  #性別
  enum sex: { man: 1, woman: 2, other: 0 }
  validates :sex, inclusion: { in: Member.sexes.keys }

  #年齢
  enum age: { teens: 0, twenties: 1, thirties: 2, forties: 3, fifties: 4, sixties: 5, seventies: 6, eighties: 7 }
  validates :age, inclusion: { in: Member.ages.keys }

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	before_action :authenticate_member!

  def show
    @member = Member.find(params[:id])
    @area = Area.find(@member.area_id)

    #アクセス制限
    if current_member.id != @member.id
      redirect_to root_path
    end
  end

  def edit
    @member = Member.find(params[:id])

    #アクセス制限
    if current_member.id != @member.id
      redirect_to root_path
    end
  end

  def update
  	@member = Member.find(params[:id])
    if @member.update(member_params)
      flash[:notice] = "会員情報が変更できました！"
      redirect_to member_path(@member.id)
    else
      render "edit"
    end
  end

  def leave
  end

  def out
  	@member = Member.find(current_member.id)
    @member.update(is_deleted: true)
    reset_session
    flash[:notice] = "ご利用ありがとうございました。またのご利用をお待ちしております！"
    redirect_to root_path
  end

  private
  def member_params
    params.require(:member).permit(:name, :email, :sex, :age, :area_id)
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/edit.html.erb
<div class="row">
	<div class="col-xs-3"></div>
	<div class="col-xs-9">
		<div>
			<h3 class="member_edit_title">登録情報編集</h3>
		</div>

		<!-- 会員情報変更フォームここから -->
		<div>
			<%= form_with(model: @member, url: member_path(@member), method: :patch) do |f| %>
				<div class="form-group">
			    <%= f.label :name, "名前orニックネーム" %><br />
			    <%= f.text_field :name, autofocus: true %>
			  </div>

			  <div class="form-group">
			    <%= f.label :email, "メールアドレス（非公開）" %><br />
			    <%= f.email_field :email %>
			  </div>

			  <div class="form-group">
			    <%= f.label :sex, "性別" %><br />
			    <%= f.collection_radio_buttons :sex, Member.sexes_i18n, :first, :last %>
			  </div>

			  <div class="form-group">
			    <%= f.label :age, "年齢" %><br />
			    <%= f.select :age, Member.ages.keys.map { |k| [I18n.t("enums.member.age.#{k}"), k] }, { include_blank: "選択してください"}  %>
			  </div>

			  <div class="form-group">
			    <%= f.label :area_id, "お住まいの地域" %><br />
		    	<%= f.collection_select(:area_id, Area.all, :id, :name) %>
			  </div>

			  <div>
			  	<%= f.submit "　編集内容を保存する　", class: "btn btn-primary" %>
			  	<%= link_to "　退会する　", leave_path(current_member), class: "btn btn-danger" %>
			  </div>
			<% end %>
		</div>
		<!-- 会員情報変更フォームここまで -->
	</div>
</div>

app/views/members/leave.html.erb
<div class="member_leave_area">
	<div>
		<h1 class="member_leave_title">本当に退会しますか？</h1>
	</div>

	<div>
		<h2>
			退会すると、会員情報や各生鮮食品の相場、<br>
			これまでの投稿等が閲覧できなくなります。<br>
			退会する場合は、「退会する」をクリックしてください。
		</h2>
	</div>

	<div>
		<%= link_to "退会しない", edit_member_path(current_member), class: "btn btn-primary" %>
		<%= link_to "退会する", members_out_path(current_member), method: :patch, class: "btn btn-danger" %>
	</div>
</div>

app/views/members/show.html.erb
<div class="row">
	<div class="col-xs-3"></div>
	<div class="col-xs-9">
		<%= flash[:notice] %>
		<div>
			<h3 class="member_show_title">マイページ</h3>
		</div>


		<div>
			<h4>登録情報</h4>
			<%= link_to "　編集する　", edit_member_path(current_member), class: "btn btn-primary" %>
			<%= link_to "　パスワードを変更する　", edit_member_registration_path, class: "btn btn-primary" %>
		</div>

		<!-- 会員情報一覧 -->
		<div>
			<table class="table table-bordered member_show_table">
				<tbody>
					<tr>
						<td class="action">名前 or ニックネーム</td>
						<td><%= @member.name %></td>
					</tr>
					<tr>
						<td class="action">メールアドレス</td>
						<td><%= @member.email %></td>
					</tr>
					<tr>
						<td class="action">性別</td>
						<td><%= @member.sex_i18n %></td>
					</tr>
					<tr>
						<td class="action">年齢</td>
						<td><%= @member.age_i18n %></td>
					</tr>
					<tr>
						<td class="action">お住まいの地域</td>
						<td><%= @area.name %></td>
					</tr>
				</tbody>
			</table>
		</div>
		<!-- 会員情報一覧ここまで -->

		<div>
			<h4>投稿一覧</h4>
			<%= link_to "投稿内容一覧を見る", posts_index_path(current_member), class: "btn btn-primary" %>
		</div>
	</div>
</div>